name: githubAction_Demo
on:
  push :
    branches:
    - main

jobs:
  my_job:
    name: my_job
    runs-on: windows-2019
    strategy:
      matrix:
        node_version: ['8', '10', '12']
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: |
        node ./index.js
  
  
