name: githubAction_Demo
on:
  push :
    branches:
    - main

jobs:
  my_job:
    name: my_job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - run: |
        npm install axios@1.1.0
        node ./demo.js
      env:
        CORPID: ${{ secrets.CORPID }}
        CORPSECRET: ${{ secrets.CORPSECRET }}
      
  
  
